apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-tls-certificate
  namespace: default
spec:
  dnsNames:
    - yatzy-api.badal.se
  secretName: letsencrypt-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer 
