apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbservice
  template:
    metadata:
      labels:
        app: dbservice
    spec:
      containers:
        - name: dbservice
          image: leebadal1/yatzy-dbservice:v1.03
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: POSTGRES_PASSWORD
            - name: ENV
              value: "production"
            
          # Other environment variables and configuration as needed

