// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: dbservice.proto

package dbservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Players         []*GameState_Player `protobuf:"bytes,1,rep,name=Players,proto3" json:"Players,omitempty"`
	CurrentPlayer   int32               `protobuf:"varint,2,opt,name=CurrentPlayer,proto3" json:"CurrentPlayer,omitempty"`
	RollsLeft       int32               `protobuf:"varint,3,opt,name=RollsLeft,proto3" json:"RollsLeft,omitempty"`
	Dice            []int32             `protobuf:"varint,4,rep,packed,name=Dice,proto3" json:"Dice,omitempty"`
	RoundsLeft      int32               `protobuf:"varint,5,opt,name=RoundsLeft,proto3" json:"RoundsLeft,omitempty"`
	CategoryChoice  string              `protobuf:"bytes,6,opt,name=CategoryChoice,proto3" json:"CategoryChoice,omitempty"`
	ScoreCalculator *GameState_Score    `protobuf:"bytes,7,opt,name=ScoreCalculator,proto3" json:"ScoreCalculator,omitempty"`
	Uuid            string              `protobuf:"bytes,8,opt,name=Uuid,proto3" json:"Uuid,omitempty"`
}

func (x *GameState) Reset() {
	*x = GameState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_dbservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_dbservice_proto_rawDescGZIP(), []int{0}
}

func (x *GameState) GetPlayers() []*GameState_Player {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetCurrentPlayer() int32 {
	if x != nil {
		return x.CurrentPlayer
	}
	return 0
}

func (x *GameState) GetRollsLeft() int32 {
	if x != nil {
		return x.RollsLeft
	}
	return 0
}

func (x *GameState) GetDice() []int32 {
	if x != nil {
		return x.Dice
	}
	return nil
}

func (x *GameState) GetRoundsLeft() int32 {
	if x != nil {
		return x.RoundsLeft
	}
	return 0
}

func (x *GameState) GetCategoryChoice() string {
	if x != nil {
		return x.CategoryChoice
	}
	return ""
}

func (x *GameState) GetScoreCalculator() *GameState_Score {
	if x != nil {
		return x.ScoreCalculator
	}
	return nil
}

func (x *GameState) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type AddGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	GameState *GameState `protobuf:"bytes,2,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
}

func (x *AddGameRequest) Reset() {
	*x = AddGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGameRequest) ProtoMessage() {}

func (x *AddGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGameRequest.ProtoReflect.Descriptor instead.
func (*AddGameRequest) Descriptor() ([]byte, []int) {
	return file_dbservice_proto_rawDescGZIP(), []int{1}
}

func (x *AddGameRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AddGameRequest) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

type AddGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AddGameResponse) Reset() {
	*x = AddGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGameResponse) ProtoMessage() {}

func (x *AddGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGameResponse.ProtoReflect.Descriptor instead.
func (*AddGameResponse) Descriptor() ([]byte, []int) {
	return file_dbservice_proto_rawDescGZIP(), []int{2}
}

func (x *AddGameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *GetGameRequest) Reset() {
	*x = GetGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameRequest) ProtoMessage() {}

func (x *GetGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameRequest.ProtoReflect.Descriptor instead.
func (*GetGameRequest) Descriptor() ([]byte, []int) {
	return file_dbservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	GameState *GameState `protobuf:"bytes,2,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
}

func (x *GetGameResponse) Reset() {
	*x = GetGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameResponse) ProtoMessage() {}

func (x *GetGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameResponse.ProtoReflect.Descriptor instead.
func (*GetGameResponse) Descriptor() ([]byte, []int) {
	return file_dbservice_proto_rawDescGZIP(), []int{4}
}

func (x *GetGameResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetGameResponse) GetGameState() *GameState {
	if x != nil {
		return x.GameState
	}
	return nil
}

type GameState_Player struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string           `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Score *GameState_Score `protobuf:"bytes,2,opt,name=Score,proto3" json:"Score,omitempty"`
}

func (x *GameState_Player) Reset() {
	*x = GameState_Player{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameState_Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState_Player) ProtoMessage() {}

func (x *GameState_Player) ProtoReflect() protoreflect.Message {
	mi := &file_dbservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState_Player.ProtoReflect.Descriptor instead.
func (*GameState_Player) Descriptor() ([]byte, []int) {
	return file_dbservice_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GameState_Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameState_Player) GetScore() *GameState_Score {
	if x != nil {
		return x.Score
	}
	return nil
}

type GameState_Score struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Chance        int32 `protobuf:"varint,1,opt,name=Chance,proto3" json:"Chance,omitempty"`
	Fives         int32 `protobuf:"varint,2,opt,name=Fives,proto3" json:"Fives,omitempty"`
	FourOfAKind   int32 `protobuf:"varint,3,opt,name=FourOfAKind,proto3" json:"FourOfAKind,omitempty"`
	Fours         int32 `protobuf:"varint,4,opt,name=Fours,proto3" json:"Fours,omitempty"`
	FullHouse     int32 `protobuf:"varint,5,opt,name=FullHouse,proto3" json:"FullHouse,omitempty"`
	LargeStraight int32 `protobuf:"varint,6,opt,name=LargeStraight,proto3" json:"LargeStraight,omitempty"`
	OnePair       int32 `protobuf:"varint,7,opt,name=OnePair,proto3" json:"OnePair,omitempty"`
	Ones          int32 `protobuf:"varint,8,opt,name=Ones,proto3" json:"Ones,omitempty"`
	Sixes         int32 `protobuf:"varint,9,opt,name=Sixes,proto3" json:"Sixes,omitempty"`
	SmallStraight int32 `protobuf:"varint,10,opt,name=SmallStraight,proto3" json:"SmallStraight,omitempty"`
	ThreeOfAKind  int32 `protobuf:"varint,11,opt,name=ThreeOfAKind,proto3" json:"ThreeOfAKind,omitempty"`
	Threes        int32 `protobuf:"varint,12,opt,name=Threes,proto3" json:"Threes,omitempty"`
	TwoPairs      int32 `protobuf:"varint,13,opt,name=TwoPairs,proto3" json:"TwoPairs,omitempty"`
	Twos          int32 `protobuf:"varint,14,opt,name=Twos,proto3" json:"Twos,omitempty"`
	Yatzy         int32 `protobuf:"varint,15,opt,name=Yatzy,proto3" json:"Yatzy,omitempty"`
}

func (x *GameState_Score) Reset() {
	*x = GameState_Score{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dbservice_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameState_Score) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState_Score) ProtoMessage() {}

func (x *GameState_Score) ProtoReflect() protoreflect.Message {
	mi := &file_dbservice_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState_Score.ProtoReflect.Descriptor instead.
func (*GameState_Score) Descriptor() ([]byte, []int) {
	return file_dbservice_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GameState_Score) GetChance() int32 {
	if x != nil {
		return x.Chance
	}
	return 0
}

func (x *GameState_Score) GetFives() int32 {
	if x != nil {
		return x.Fives
	}
	return 0
}

func (x *GameState_Score) GetFourOfAKind() int32 {
	if x != nil {
		return x.FourOfAKind
	}
	return 0
}

func (x *GameState_Score) GetFours() int32 {
	if x != nil {
		return x.Fours
	}
	return 0
}

func (x *GameState_Score) GetFullHouse() int32 {
	if x != nil {
		return x.FullHouse
	}
	return 0
}

func (x *GameState_Score) GetLargeStraight() int32 {
	if x != nil {
		return x.LargeStraight
	}
	return 0
}

func (x *GameState_Score) GetOnePair() int32 {
	if x != nil {
		return x.OnePair
	}
	return 0
}

func (x *GameState_Score) GetOnes() int32 {
	if x != nil {
		return x.Ones
	}
	return 0
}

func (x *GameState_Score) GetSixes() int32 {
	if x != nil {
		return x.Sixes
	}
	return 0
}

func (x *GameState_Score) GetSmallStraight() int32 {
	if x != nil {
		return x.SmallStraight
	}
	return 0
}

func (x *GameState_Score) GetThreeOfAKind() int32 {
	if x != nil {
		return x.ThreeOfAKind
	}
	return 0
}

func (x *GameState_Score) GetThrees() int32 {
	if x != nil {
		return x.Threes
	}
	return 0
}

func (x *GameState_Score) GetTwoPairs() int32 {
	if x != nil {
		return x.TwoPairs
	}
	return 0
}

func (x *GameState_Score) GetTwos() int32 {
	if x != nil {
		return x.Twos
	}
	return 0
}

func (x *GameState_Score) GetYatzy() int32 {
	if x != nil {
		return x.Yatzy
	}
	return 0
}

var File_dbservice_proto protoreflect.FileDescriptor

var file_dbservice_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x62, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x64, 0x62, 0x22, 0x97, 0x06, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x07, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x43, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x6f, 0x6c,
	0x6c, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x52, 0x6f,
	0x6c, 0x6c, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x69, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x44, 0x69, 0x63, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52,
	0x6f, 0x75, 0x6e, 0x64, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x73, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x43, 0x68, 0x6f,
	0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0f, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64,
	0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x52, 0x0f, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x75, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x55, 0x75, 0x69, 0x64, 0x1a, 0x47, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x64, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x1a,
	0x9d, 0x03, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x61,
	0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x69, 0x76, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x46, 0x69, 0x76, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x6f, 0x75, 0x72, 0x4f,
	0x66, 0x41, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x46, 0x6f,
	0x75, 0x72, 0x4f, 0x66, 0x41, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6f, 0x75,
	0x72, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x46, 0x6f, 0x75, 0x72, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x46, 0x75, 0x6c, 0x6c, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x46, 0x75, 0x6c, 0x6c, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x53, 0x74, 0x72, 0x61, 0x69, 0x67, 0x68, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x53, 0x74, 0x72, 0x61, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x6e, 0x65, 0x50, 0x61, 0x69, 0x72, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4f, 0x6e, 0x65, 0x50, 0x61, 0x69, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x4f, 0x6e, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4f, 0x6e, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x69, 0x78, 0x65, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x53, 0x69, 0x78, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x6d, 0x61, 0x6c, 0x6c,
	0x53, 0x74, 0x72, 0x61, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x72, 0x61, 0x69, 0x67, 0x68, 0x74, 0x12, 0x22, 0x0a,
	0x0c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x4f, 0x66, 0x41, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x54, 0x68, 0x72, 0x65, 0x65, 0x4f, 0x66, 0x41, 0x4b, 0x69, 0x6e,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x68, 0x72, 0x65, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x54, 0x68, 0x72, 0x65, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x77, 0x6f,
	0x50, 0x61, 0x69, 0x72, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x54, 0x77, 0x6f,
	0x50, 0x61, 0x69, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x77, 0x6f, 0x73, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x54, 0x77, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x59, 0x61, 0x74,
	0x7a, 0x79, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x59, 0x61, 0x74, 0x7a, 0x79, 0x22,
	0x52, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x2c, 0x0a,
	0x0a, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x32, 0x79, 0x0a, 0x0f, 0x44,
	0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x2e, 0x64, 0x62, 0x2e, 0x41,
	0x64, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x64, 0x62, 0x2e, 0x41, 0x64, 0x64, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x2e,
	0x64, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x64, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x79, 0x61, 0x74, 0x7a, 0x79, 0x2f,
	0x63, 0x6d, 0x64, 0x2f, 0x64, 0x62, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dbservice_proto_rawDescOnce sync.Once
	file_dbservice_proto_rawDescData = file_dbservice_proto_rawDesc
)

func file_dbservice_proto_rawDescGZIP() []byte {
	file_dbservice_proto_rawDescOnce.Do(func() {
		file_dbservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_dbservice_proto_rawDescData)
	})
	return file_dbservice_proto_rawDescData
}

var file_dbservice_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dbservice_proto_goTypes = []interface{}{
	(*GameState)(nil),        // 0: db.GameState
	(*AddGameRequest)(nil),   // 1: db.AddGameRequest
	(*AddGameResponse)(nil),  // 2: db.AddGameResponse
	(*GetGameRequest)(nil),   // 3: db.GetGameRequest
	(*GetGameResponse)(nil),  // 4: db.GetGameResponse
	(*GameState_Player)(nil), // 5: db.GameState.Player
	(*GameState_Score)(nil),  // 6: db.GameState.Score
}
var file_dbservice_proto_depIdxs = []int32{
	5, // 0: db.GameState.Players:type_name -> db.GameState.Player
	6, // 1: db.GameState.ScoreCalculator:type_name -> db.GameState.Score
	0, // 2: db.AddGameRequest.game_state:type_name -> db.GameState
	0, // 3: db.GetGameResponse.game_state:type_name -> db.GameState
	6, // 4: db.GameState.Player.Score:type_name -> db.GameState.Score
	1, // 5: db.DatabaseService.AddGame:input_type -> db.AddGameRequest
	3, // 6: db.DatabaseService.GetGame:input_type -> db.GetGameRequest
	2, // 7: db.DatabaseService.AddGame:output_type -> db.AddGameResponse
	4, // 8: db.DatabaseService.GetGame:output_type -> db.GetGameResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_dbservice_proto_init() }
func file_dbservice_proto_init() {
	if File_dbservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dbservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameState_Player); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dbservice_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameState_Score); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dbservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dbservice_proto_goTypes,
		DependencyIndexes: file_dbservice_proto_depIdxs,
		MessageInfos:      file_dbservice_proto_msgTypes,
	}.Build()
	File_dbservice_proto = out.File
	file_dbservice_proto_rawDesc = nil
	file_dbservice_proto_goTypes = nil
	file_dbservice_proto_depIdxs = nil
}
